### ISSUE TITLE
Rewrite the styles

### ISSUE THREAD

**Issue by UltiRequiem** [UltiRequiem/example-html-css-esm#1]
Make it cool, it has to have a header, main and footer section.

**Comment by harshlancer** [comment]
I think I can do it ...

**Comment by UltiRequiem** [comment]
That would be cool, go ahead @harshlancer 🚀

**Comment by tacosontitan** [comment]
@harshlancer beat me to it lol noice

**Comment by UltiRequiem** [comment]
> beat me to it lol noice

you can try with this easy one if you know React 👇🏽 

https://github.com/UltiRequiem/ulticlock/issues/1

This one is harder, using Svelte 😄 

https://github.com/UltiRequiem/ultitodo/issues/2

**Comment by UltiRequiem** [comment]
Join [my discord server](https://discord.gg/XW8mK5yu5R) if you have any questions 😎

**Comment by UltiRequiem** [comment]
Hey @tacosontitan, you can take it now if you want 🚀

**Comment by UltiRequiem** [comment]
Done
